### ISSUE TITLE
[Bug] Recalculate score for saved builds

### ISSUE THREAD

**Issue by fribbels** [fribbels/hsr-optimizer#170]
### Motivation

Currently the saved builds scores are static and don't update when the scoring algorithm changes

### Objective

Re-apply the scoring algorithm when opening the saves builds menu. This should take into account custom scoring updates.

**Comment by kaixin-hc** [comment]
i'll give this a shot!

**Comment by kaixin-hc** [comment]
Transferring discord discussion here if someone finds this in the future:

The key issue here is that the two numbers don't match - and this is confusing for the user: 
<img width="1470" alt="ss of scroing not updating" src="https://github.com/fribbels/hsr-optimizer/assets/59471320/29bfd760-2e86-4511-9727-05a7f30d58cc">

There are use cases where you might not want to update your saved build with the most recent algorithm, such as with characters who can have multiple build profiles: (see #35 for more discussion. When #35 is implemented, scores will eventually be attached to scoring profiles instead of characters. The build itself should be saved with a profile attached to it instead of the behaviour we have now in the fix)

One obvious issue with mantaining build's score based on the scoring algorithm when it was saved is the user will probably forget what their custom settings were, and it'd be a whole bunch more (out of scope) work to make a UI that makes sense for this.

so the fix for this bug is just to get the two numbers to match by updating the saved builds since "we want to score both the character and its saved builds by the current user defined scoring algorithm".
